services:
  docs-swarmauri-com:
    build: .
    container_name: docs-swarmauri-com
    restart: unless-stopped
    labels:
      site.host: docs.swarmauri.com
      site.kind: zdx-docs
    expose:
      - "80"
    networks:
      dockerwp:
        aliases:
          - docs-swarmauri-com

networks:
  dockerwp:
    name: dockerwp
    external: true
